### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by 9037568** [awslabs/rds-data-api-client-library-java#5]
Attempting to run the code fragment below (based on [this AWS example](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html#data-api.java-client-library)) reveals missing dependencies.

````
    RdsDataClient client = RdsDataClient.builder().database(Database)
                           .resourceArn(Database_Resource_ARN)
                           .secretArn(Database_Secret_ARN).build();
    client.forSql("select * from accounts").execute().mapToSingle(File.class);
````

Error message:

````
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/base/Strings
        at com.amazon.rdsdata.client.RdsDataClient.forSql(RdsDataClient.java:97)
        at data1.main(data1.java:15)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Strings
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 2 more
````

**Comment by TheAshwanik** [comment]
1 year later, still seeing this issue, Has anyone managed to fix this?

**Comment by sp0l** [comment]
com.google.common.base.Strings is part of Guava. Guava is already listed in the dependencies section of build.gradle.

**Comment by TheAshwanik** [comment]
Yes noticed it. And when I added Guava in my Lambda layer, it still failed. then I added it in individual POM.xml within the different lambdas. It worked.

**Comment by sorin-costea** [comment]
Many dependencies of the RDS client are marked as "runtime" thus will be missed at compile time. Maybe that's your problem?
